authors:
  hpt:
    name: Dr. Hari Thapliyal
    description: Author
    avatar: https://avatars.githubusercontent.com/u/4255142
    url: https://github.com/dasarpai
  hpt1:
    name: Dr. Hari Thapliyal
    description: Solution Architect
    avatar: https://avatars.githubusercontent.com/u/4255142
    url: https://github.com/dasarpai